### ISSUE TITLE
Memcached

### ISSUE THREAD

**Issue by tamalsaha** [kubedb/operator#128]
__This is an umbrella issue to capture various features of Memcached__

- [ ] Replica > 1
- [ ] StatefulSet vs Deployment 
- [ ] Run as Critical Pod (pod disruption budget)
- [ ] Prometheus Monitoring
- [ ] Proxy (sharding, connection pooling)
  -  https://github.com/twitter/twemproxy
  - https://github.com/Netflix/rend

**Comment by tamalsaha** [comment]
This issue was moved to kubedb/project#43
